import openai
import numpy as np
import pandas as pd
from sklearn.metrics.pairwise import cosine_similarity
import tiktoken
import ssl
import matplotlib.pyplot as plt
import seaborn as sns

# Set your OpenAI API key

openai.api_key = "API_KEY"

# Load data
df = pd.read_csv("data/updated_data_2023.csv")

# Function to get text and file names by industry
def get_text_and_files_by_industry(input_industry):
    filtered_data = df[df['SIC'] == input_industry]
    if filtered_data.empty:
        raise ValueError("No files found for the given industry.")
    if len(filtered_data) < 10:
        raise ValueError("Less than 10 files found for the given industry.")
    # return filtered_data['Text'].tolist()[:10], filtered_data['File'].tolist()[:10]
    return filtered_data.head(10)

# Function to split text into chunks
def split_text_by_tokens(text, max_tokens=8192, model="text-embedding-ada-002"):
    tokenizer = tiktoken.encoding_for_model(model)
    tokens = tokenizer.encode(text)
    chunks = []
    
    # Split tokens into chunks
    for i in range(0, len(tokens), max_tokens):
        chunk_tokens = tokens[i:i + max_tokens]
        chunk_text = tokenizer.decode(chunk_tokens)
        if chunk_text.strip():  # Ensure chunk is not empty
            chunks.append(chunk_text)
    
    return chunks

# Function to generate embeddings for a single chunk
def generate_embedding(text):
    try:
        response = openai.embeddings.create(
            input=text,
            model="text-embedding-ada-002"
        )
        return response.data[0].embedding
    except Exception as e:
        print(f"Error generating embedding: {e}")
        return None  # Return None on failure

# Function to combine embeddings
def combine_embeddings(embeddings):
    valid_embeddings = [e for e in embeddings if e is not None]  # Ignore None values
    if not valid_embeddings:
        raise ValueError("No valid embeddings to combine.")
    return np.nanmean(valid_embeddings, axis=0).tolist()  # Use nanmean to handle NaN

# Process a single large text
def process_large_text(text):
    # Step 1: Split the text into chunks
    chunks = split_text_by_tokens(text, max_tokens=8191)  # Reserve 1 token for safety
    print(f"Split text into {len(chunks)} chunks.")

    # Step 2: Generate embeddings for each chunk
    chunk_embeddings = []
    for i, chunk in enumerate(chunks):
        print(f"Generating embedding for chunk {i+1}/{len(chunks)}...")
        chunk_embedding = generate_embedding(chunk)
        if chunk_embedding is not None:  # Only append valid embeddings
            chunk_embeddings.append(chunk_embedding)

    # Step 3: Combine chunk embeddings
    if not chunk_embeddings:
        raise ValueError("No valid embeddings were generated.")
    final_embedding = combine_embeddings(chunk_embeddings)
    return final_embedding

# Generate embeddings for multiple texts
def generate_embeddings_for_texts(text_list):
    embeddings = []
    for idx, text in enumerate(text_list):
        print(f"Processing text {idx + 1}/{len(text_list)}...")
        embedding = process_large_text(text)  # Process each large text
        embeddings.append(embedding)
    return embeddings

# Function to compute cosine similarity
def compute_cosine_similarity(embeddings):
    embedding_matrix = np.array(embeddings)
    similarity_matrix = cosine_similarity(embedding_matrix)
    return similarity_matrix

def plot_similarity_heatmap(similarity_matrix, labels):
    # Set figure dimensions and axes
    fig, ax = plt.subplots(figsize=(12, 12))  # Adjust size to fit labels and center
    sns.heatmap(
        similarity_matrix,
        xticklabels=labels,
        yticklabels=labels,
        cmap="viridis",
        annot=True,
        fmt=".2f",
        cbar=True,
        ax=ax
    )
    
    # Set title and labels with padding
    ax.set_title("Cosine Similarity Heatmap", pad=20)
    ax.set_xlabel("Firms", labelpad=20)
    ax.set_ylabel("Firms", labelpad=20)
    
    # Rotate labels
    ax.set_xticklabels(ax.get_xticklabels(), rotation=45, ha="right")
    ax.set_yticklabels(ax.get_yticklabels(), rotation=0)
    
    # Adjust layout
    plt.subplots_adjust(left=0.3, right=0.95, top=0.9, bottom=0.3)  # Add padding to center heatmap
    
    plt.show()

def save_embeddings_to_csv(embeddings, labels, output_csv_path):
  
    # Create a DataFrame
    data = {
        "File": labels,  # Firm labels
        "Embedding": [",".join(map(str, embedding)) for embedding in embeddings]  # Convert embeddings to string
    }
    df_embeddings = pd.DataFrame(data)
    
    # Save to CSV
    df_embeddings.to_csv(output_csv_path, index=False)
    print(f"Embeddings saved to {output_csv_path}")


# Main execution
if __name__ == "__main__":
    try:
        # Get 10 texts and file names for a specific industry
        # input_industry = "AGRICULTURE CHEMICALS [2870]" ## select the indusry you want to compare (> 10 companies)
        input_industry = 'FIRE, MARINE & CASUALTY INSURANCE [6331]'
        # output_text_list, firm_labels = get_text_and_files_by_industry(input_industry)
        df = get_text_and_files_by_industry(input_industry)
        output_text_list, firm_labels = df['Text'].tolist(), df['File'].tolist()
        
        # Generate embeddings for all 10 texts
        print("Generating embeddings for all 10 texts...")
        embeddings = generate_embeddings_for_texts(output_text_list)

        output_csv_path = "embeddings_output.csv"
        save_embeddings_to_csv(embeddings, firm_labels, output_csv_path)
    

        # Calculate cosine similarity matrix
        print("Calculating cosine similarity matrix...")
        similarity_matrix = compute_cosine_similarity(embeddings)

        # Plot similarity heatmap
        plot_similarity_heatmap(similarity_matrix, firm_labels)
    
    except Exception as e:
        print(f"An error occurred: {e}")


#------------------------------------------------------# full industry list #------------------------------------------------------#
# ['ABRASIVE ASBESTOS & MISC NONMETALLIC MINERAL PRODUCTS [3290]'
#  'ACCIDENT & HEALTH INSURANCE [6321]' 'ADHESIVES & SEALANTS [2891]'
#  'AGRICULTURE CHEMICALS [2870]' 'AGRICULTURE PRODUCTION - CROPS [0100]'
#  'AGRICULTURE PRODUCTION - LIVESTOCK & ANIMAL SPECIALTIES [0200]'
#  'AGRICULTURE SERVICES [0700]'
#  'AIR COND & WARM AIR HEATING EQUIP & COMM & INDL REFRIG EQUIP [3585]'
#  'AIR COURIER SERVICES [4513]' 'AIR TRANSPORTATION, NONSCHEDULED [4522]'
#  'AIR TRANSPORTATION, SCHEDULED [4512]' 'AIRCRAFT & PARTS [3720]'
#  'AIRCRAFT ENGINES & ENGINE PARTS [3724]'
#  'AIRCRAFT PART & AUXILIARY EQUIPMENT, NEC [3728]' 'AIRCRAFT [3721]'
#  'AIRPORTS, FLYING FIELDS & AIRPORT TERMINAL SERVICES [4581]'
#  'APPAREL & OTHER FINISHED PRODS OF FABRICS & SIMILAR MATERIAL [2300]'
#  'ARRANGEMENT OF TRANSPORTATION OF FREIGHT & CARGO [4731]'
#  'AUTO CONTROLS FOR REGULATING RESIDENTIAL & COMML ENVIRONMENT [3822]'
#  'BAKERY PRODUCTS [2050]' 'BALL & ROLLER BEARINGS [3562]'
#  'BEVERAGES [2080]'
#  'BIOLOGICAL PRODUCTS (NO DIAGNOSTIC SUBSTANCES) [2836]'
#  'BITUMINOUS COAL & LIGNITE MINING [1220]'
#  'BITUMINOUS COAL & LIGNITE SURFACE MINING [1221]' 'BLANK CHECKS [6770]'
#  'BLANKBOOKS, LOOSELEAF BINDERS & BOOKBINDING & RELATED WORK [2780]'
#  'BOOKS: PUBLISHING OR PUBLISHING AND PRINTING [2731]'
#  'BOTTLED & CANNED SOFT DRINKS CARBONATED WATERS [2086]'
#  'BROADWOVEN FABRIC MILLS, COTTON [2211]'
#  'BROADWOVEN FABRIC MILS, MAN MADE FIBER & SILK [2221]'
#  'CABLE & OTHER PAY TELEVISION SERVICES [4841]'
#  'CALCULATING & ACCOUNTING MACHINES (NO ELECTRONIC COMPUTERS) [3578]'
#  'CANNED, FROZEN & PRESERVED FRUIT, VEG & FOOD SPECIALTIES [2030]'
#  'CANNED, FRUITS, VEG & PRESERVES, JAMS & JELLIES [2033]'
#  'CARPETS AND RUGS [2273]' 'CEMENT, HYDRAULIC [3241]'
#  'CHEMICALS & ALLIED PRODUCTS [2800]' 'CIGARETTES [2111]'
#  'COATING, ENGRAVING & ALLIED SERVICES [3470]'
#  'COGENERATION SERVICES & SMALL POWER PRODUCERS [4991]'
#  'COMMERCIAL BANKS, NEC [6029]' 'COMMERCIAL PRINTING [2750]'
#  'COMMODITY CONTRACTS BROKERS & DEALERS [6221]'
#  'COMMUNICATION SERVICES, NEC [4899]'
#  'COMMUNICATIONS EQUIPMENT, NEC [3669]'
#  'COMPUTER & OFFICE EQUIPMENT [3570]'
#  'COMPUTER COMMUNICATIONS EQUIPMENT [3576]'
#  'COMPUTER PERIPHERAL EQUIPMENT, NEC [3577]'
#  'COMPUTER STORAGE DEVICES [3572]'
#  'CONCRETE PRODUCTS, EXCEPT BLOCK & BRICK [3272]'
#  'CONSTRUCTION MACHINERY & EQUIP [3531]'
#  'CONSTRUCTION SPECIAL TRADE CONTRACTORS [1700]'
#  'CONSTRUCTION, MINING & MATERIALS HANDLING MACHINERY & EQUIP [3530]'
#  'CONVERTED PAPER & PAPERBOARD PRODS (NO CONTAINERS/BOXES) [2670]'
#  'COOKIES & CRACKERS [2052]' 'CRUDE PETROLEUM & NATURAL GAS [1311]'
#  'CUTLERY, HANDTOOLS & GENERAL HARDWARE [3420]' 'DAIRY PRODUCTS [2020]'
#  'DEEP SEA FOREIGN TRANSPORTATION OF FREIGHT [4412]'
#  'DENTAL EQUIPMENT & SUPPLIES [3843]' 'DOLLS & STUFFED TOYS [3942]'
#  'DRAWING AND INSULATING NONFERROUS WIRE [3357]'
#  'DRILLING OIL & GAS WELLS [1381]'
#  'ELECTRIC & OTHER SERVICES COMBINED [4931]'
#  'ELECTRIC HOUSEWARES & FANS [3634]'
#  'ELECTRIC LIGHTING & WIRING EQUIPMENT [3640]' 'ELECTRIC SERVICES [4911]'
#  'ELECTRIC, GAS & SANITARY SERVICES [4900]'
#  'ELECTRICAL INDUSTRIAL APPARATUS [3620]' 'ELECTRICAL WORK [1731]'
#  'ELECTROMEDICAL & ELECTROTHERAPEUTIC APPARATUS [3845]'
#  'ELECTRONIC & OTHER ELECTRICAL EQUIPMENT (NO COMPUTER EQUIP) [3600]'
#  'ELECTRONIC COILS, TRANSFORMERS & OTHER INDUCTORS [3677]'
#  'ELECTRONIC COMPONENTS & ACCESSORIES [3670]'
#  'ELECTRONIC COMPONENTS, NEC [3679]' 'ELECTRONIC COMPUTERS [3571]'
#  'ELECTRONIC CONNECTORS [3678]' 'ENGINES & TURBINES [3510]'
#  'FABRICATED PLATE WORK (BOILER SHOPS) [3443]'
#  'FABRICATED RUBBER PRODUCTS, NEC [3060]'
#  'FABRICATED STRUCTURAL METAL PRODUCTS [3440]'
#  'FARM MACHINERY & EQUIPMENT [3523]' 'FATS & OILS [2070]'
#  'FEDERAL & FEDERALLY-SPONSORED CREDIT AGENCIES [6111]'
#  'FINANCE SERVICES [6199]' 'FIRE, MARINE & CASUALTY INSURANCE [6331]'
#  'FISHING, HUNTING & TRAPPING [0900]' 'FLAT GLASS [3211]'
#  'FOOD & KINDRED PRODUCTS [2000]' 'FOOTWEAR, (NO RUBBER) [3140]'
#  'FUNCTIONS RELATED TO DEPOSITORY BANKING, NEC [6099]'
#  "GAMES, TOYS & CHILDREN'S VEHICLES (NO DOLLS & BICYCLES) [3944]"
#  'GAS & OTHER SERVICES COMBINED [4932]'
#  'GASKETS, PACKAGING AND SEALING DEVICES & RUBBER & PLASTIC HOSE [3050]'
#  'GEN BUILDING CONTRACTORS - RESIDENTIAL BUILDINGS [1520]'
#  'GENERAL BUILDING CONTRACTORS - NONRESIDENTIAL BUILDINGS [1540]'
#  'GENERAL INDUSTRIAL MACHINERY & EQUIPMENT [3560]'
#  'GENERAL INDUSTRIAL MACHINERY & EQUIPMENT, NEC [3569]'
#  'GLASS CONTAINERS [3221]'
#  'GLASS PRODUCTS, MADE OF PURCHASED GLASS [3231]'
#  'GOLD & SILVER ORES [1040]' 'GRAIN MILL PRODUCTS [2040]'
#  'GUIDED MISSILES & SPACE VEHICLES & PARTS [3760]'
#  'HAZARDOUS WASTE MANAGEMENT [4955]'
#  'HEATING EQUIP, EXCEPT ELEC & WARM AIR & PLUMBING FIXTURES [3430]'
#  'HEATING EQUIPMENT, EXCEPT ELECTRIC & WARM AIR FURNACES [3433]'
#  'HEAVY CONSTRUCTION OTHER THAN BUILDING CONST - CONTRACTORS [1600]'
#  'HOSPITAL & MEDICAL SERVICE PLANS [6324]' 'HOTELS & MOTELS [7011]'
#  'HOTELS, ROOMING HOUSE, CAMPS & OTHER LODGING PLACES [7000]'
#  'HOUSEHOLD APPLIANCES [3630]' 'HOUSEHOLD AUDIO & VIDEO EQUIPMENT [3651]'
#  'HOUSEHOLD FURNITURE [2510]' 'ICE CREAM & FROZEN DESSERTS [2024]'
#  'IN VITRO & IN VIVO DIAGNOSTIC SUBSTANCES [2835]'
#  'INDUSTRIAL & COMMERCIAL FANS & BLOWERS & AIR PURIFYING EQUIP [3564]'
#  'INDUSTRIAL INORGANIC CHEMICALS [2810]'
#  'INDUSTRIAL INSTRUMENTS FOR MEASUREMENT, DISPLAY, AND CONTROL [3823]'
#  'INDUSTRIAL ORGANIC CHEMICALS [2860]'
#  'INDUSTRIAL TRUCKS TRACTORS TRAILERS & STACKERS [3537]'
#  'INSTRUMENTS FOR MEAS & TESTING OF ELECTRICITY & ELEC SIGNALS [3825]'
#  'INSURANCE AGENTS BROKERS & SERVICES [6411]'
#  'INSURANCE CARRIERS, NEC [6399]' 'INVESTMENT ADVICE [6282]'
#  'INVESTORS, NEC [6799]' 'JEWELRY, SILVERWARE & PLATED WARE [3910]'
#  'LABORATORY ANALYTICAL INSTRUMENTS [3826]'
#  'LABORATORY APPARATUS & FURNITURE [3821]'
#  'LAND SUBDIVIDERS & DEVELOPERS (NO CEMETERIES) [6552]'
#  'LAWN & GARDEN TRACTORS & HOME LAWN & GARDEN EQUIPMENT [3524]'
#  'LEATHER & LEATHER PRODUCTS [3100]'
#  'LESSORS OF REAL PROPERTY, NEC [6519]' 'LIFE INSURANCE [6311]'
#  'LOAN BROKERS [6163]' 'LUMBER & WOOD PRODUCTS (NO FURNITURE) [2400]'
#  'MACHINE TOOLS, METAL CUTTING TYPES [3541]' 'MALT BEVERAGES [2082]'
#  'MANIFOLD BUSINESS FORMS [2761]'
#  'MEASURING & CONTROLLING DEVICES, NEC [3829]'
#  'MEAT PACKING PLANTS [2011]'
#  'MEDICINAL CHEMICALS & BOTANICAL PRODUCTS [2833]'
#  "MEN'S & BOYS' FURNISHINGS, WORK CLOTHING, AND ALLIED GARMENTS [2320]"
#  'METAL CANS [3411]' 'METAL DOORS, SASH, FRAMES, MOLDING & TRIM [3442]'
#  'METAL FORGING & STAMPINGS [3460]' 'METAL MINING [1000]'
#  'METAL SHIPPING BARRELS, DRUMS, KEGS & PAILS [3412]'
#  'METALWORKING MACHINERY & EQUIPMENT [3540]'
#  'MILLWOOD, VENEER, PLYWOOD & STRUCTURAL WOOD MEMBERS [2430]'
#  'MINERAL ROYALTY TRADERS [6795]'
#  'MINING, QUARRYING OF NONMETALLIC MINERALS (NO FUELS) [1400]'
#  'MISC INDUSTRIAL & COMMERCIAL MACHINERY & EQUIPMENT [3590]'
#  'MISCELLANEOUS BUSINESS CREDIT INSTITUTION [6159]'
#  'MISCELLANEOUS CHEMICAL PRODUCTS [2890]'
#  'MISCELLANEOUS ELECTRICAL MACHINERY, EQUIPMENT & SUPPLIES [3690]'
#  'MISCELLANEOUS FABRICATED METAL PRODUCTS [3490]'
#  'MISCELLANEOUS FABRICATED TEXTILE PRODUCTS [2390]'
#  'MISCELLANEOUS FOOD PREPARATIONS & KINDRED PRODUCTS [2090]'
#  'MISCELLANEOUS MANUFACTURING INDUSTRIES [3990]'
#  'MISCELLANEOUS METAL ORES [1090]' 'MISCELLANEOUS PLASTIC PRODUCTS [3080]'
#  'MISCELLANEOUS PRIMARY METAL PRODUCTS [3390]'
#  'MISCELLANEOUS PRODUCTS OF PETROLEUM &  COAL [2990]'
#  'MISCELLANEOUS TRANSPORTATION EQUIPMENT [3790]' 'MOBILE HOMES [2451]'
#  'MORTGAGE BANKERS & LOAN CORRESPONDENTS [6162]' 'MOTOR HOMES [3716]'
#  'MOTOR VEHICLE PARTS & ACCESSORIES [3714]'
#  'MOTOR VEHICLES & PASSENGER CAR BODIES [3711]'
#  'MOTORCYCLES, BICYCLES & PARTS [3751]' 'MOTORS & GENERATORS [3621]'
#  'NATIONAL COMMERCIAL BANKS [6021]' 'NATURAL GAS DISTRIBUTION [4924]'
#  'NATURAL GAS TRANSMISSION & DISTRIBUTION [4923]'
#  'NATURAL GAS TRANSMISSION [4922]'
#  'NEWSPAPERS:  PUBLISHING OR PUBLISHING & PRINTING [2711]'
#  'NONFERROUS FOUNDRIES (CASTINGS) [3360]'
#  'OFFICE FURNITURE (NO WOOD) [2522]' 'OFFICE FURNITURE [2520]'
#  'OFFICE MACHINES, NEC [3579]'
#  'OIL & GAS FILED MACHINERY & EQUIPMENT [3533]'
#  'OIL AND GAS FIELD EXPLORATION SERVICES [1382]'
#  'OIL ROYALTY TRADERS [6792]' 'OIL, GAS FIELD SERVICES, NBC [1389]'
#  'OPERATIVE BUILDERS [1531]' 'OPERATORS OF APARTMENT BUILDINGS [6513]'
#  'OPERATORS OF NONRESIDENTIAL BUILDINGS [6512]' 'OPHTHALMIC GOODS [3851]'
#  'OPTICAL INSTRUMENTS & LENSES [3827]'
#  'ORDNANCE & ACCESSORIES, (NO VEHICLES/GUIDED MISSILES) [3480]'
#  'ORTHOPEDIC, PROSTHETIC & SURGICAL APPLIANCES & SUPPLIES [3842]'
#  'PAINTS, VARNISHES, LACQUERS, ENAMELS & ALLIED PRODUCTS [2851]'
#  'PAPER MILLS [2621]' 'PAPERBOARD CONTAINERS & BOXES [2650]'
#  'PAPERBOARD MILLS [2631]' 'PAPERS & ALLIED PRODUCTS [2600]'
#  'PATENT OWNERS & LESSORS [6794]'
#  'PERFUMES, COSMETICS & OTHER TOILET PREPARATIONS [2844]'
#  'PERIODICALS:  PUBLISHING OR PUBLISHING AND PRINTING [2721]'
#  'PERSONAL CREDIT INSTITUTIONS [6141]' 'PETROLEUM REFINING [2911]'
#  'PHARMACEUTICAL PREPARATIONS [2834]'
#  'PHONOGRAPH RECORDS & PRERECORDED AUDIO TAPES & DISKS [3652]'
#  'PHOTOGRAPHIC EQUIPMENT & SUPPLIES [3861]'
#  'PIPE LINES (NO NATURAL GAS) [4610]'
#  'PLASTIC MATERIAL, SYNTH RESIN/RUBBER, CELLULOS (NO GLASS) [2820]'
#  'PLASTICS FOAM PRODUCTS [3086]' 'PLASTICS PRODUCTS, NEC [3089]'
#  'PLASTICS, FOIL & COATED PAPER BAGS [2673]'
#  'PLASTICS, MATERIALS, SYNTH RESINS & NONVULCAN ELASTOMERS [2821]'
#  'POTTERY & RELATED PRODUCTS [3260]'
#  'POULTRY SLAUGHTERING AND PROCESSING [2015]'
#  'POWER, DISTRIBUTION & SPECIALTY TRANSFORMERS [3612]'
#  'PREFABRICATED METAL BUILDINGS & COMPONENTS [3448]'
#  'PREPARED FRESH OR FROZEN FISH & SEAFOODS [2092]'
#  'PRIMARY PRODUCTION OF ALUMINUM [3334]'
#  'PRIMARY SMELTING & REFINING OF NONFERROUS METALS [3330]'
#  'PRINTED CIRCUIT BOARDS [3672]'
#  'PUBLIC BUILDING AND RELATED FURNITURE [2531]' 'PULP MILLS [2611]'
#  'PUMPS & PUMPING EQUIPMENT [3561]'
#  'RADIO & TV BROADCASTING & COMMUNICATIONS EQUIPMENT [3663]'
#  'RADIO BROADCASTING STATIONS [4832]'
#  'RADIO TELEPHONE COMMUNICATIONS [4812]' 'RAILROAD EQUIPMENT [3743]'
#  'RAILROAD SWITCHING & TERMINAL ESTABLISHMENTS [4013]'
#  'RAILROADS, LINE-HAUL OPERATING [4011]'
#  'REAL ESTATE AGENTS & MANAGERS (FOR OTHERS) [6531]'
#  'REAL ESTATE INVESTMENT TRUSTS [6798]'
#  'REAL ESTATE OPERATORS (NO DEVELOPERS) & LESSORS [6510]'
#  'REAL ESTATE [6500]' 'REFRIGERATION & SERVICE INDUSTRY MACHINERY [3580]'
#  'REFUSE SYSTEMS [4953]'
#  'RETAIL- COMPUTER & PRERECORDED TAPE STORES [5735]'
#  'RETAIL-APPAREL & ACCESSORY STORES [5600]'
#  'RETAIL-AUTO & HOME SUPPLY STORES [5531]'
#  'RETAIL-AUTO DEALERS & GASOLINE STATIONS [5500]'
#  'RETAIL-BUILDING MATERIALS, HARDWARE, GARDEN SUPPLY [5200]'
#  'RETAIL-CATALOG & MAIL-ORDER HOUSES [5961]'
#  'RETAIL-COMPUTER & COMPUTER SOFTWARE STORES [5734]'
#  'RETAIL-CONVENIENCE STORES [5412]' 'RETAIL-DEPARTMENT STORES [5311]'
#  'RETAIL-DRUG STORES AND PROPRIETARY STORES [5912]'
#  'RETAIL-EATING & DRINKING PLACES [5810]' 'RETAIL-EATING PLACES [5812]'
#  'RETAIL-FAMILY CLOTHING STORES [5651]' 'RETAIL-FOOD STORES [5400]'
#  'RETAIL-FURNITURE STORES [5712]' 'RETAIL-GROCERY STORES [5411]'
#  'RETAIL-HOBBY, TOY & GAME SHOPS [5945]'
#  'RETAIL-HOME FURNITURE, FURNISHINGS & EQUIPMENT STORES [5700]'
#  'RETAIL-JEWELRY STORES [5944]'
#  'RETAIL-LUMBER & OTHER BUILDING MATERIALS DEALERS [5211]'
#  'RETAIL-MISCELLANEOUS RETAIL [5900]'
#  'RETAIL-MISCELLANEOUS SHOPPING GOODS STORES [5940]'
#  'RETAIL-NONSTORE RETAILERS [5960]'
#  'RETAIL-RADIO TV & CONSUMER ELECTRONICS STORES [5731]'
#  'RETAIL-RETAIL STORES, NEC [5990]' 'RETAIL-SHOE STORES [5661]'
#  'RETAIL-VARIETY STORES [5331]' "RETAIL-WOMEN'S CLOTHING STORES [5621]"
#  'ROLLING DRAWING & EXTRUDING OF NONFERROUS METALS [3350]'
#  'RUBBER & PLASTICS FOOTWEAR [3021]' 'SANITARY SERVICES [4950]'
#  'SAUSAGE, OTHER PREPARED MEAT PRODUCTS  [2013]'
#  'SAVINGS INSTITUTION, FEDERALLY CHARTERED [6035]'
#  'SAVINGS INSTITUTIONS, NOT FEDERALLY CHARTERED [6036]'
#  'SAWMILLS, PLANNING MILLS, GENERAL [2421]'
#  'SEARCH, DETECTION, NAVIGATION, GUIDANCE, AERONAUTICAL SYS [3812]'
#  'SECONDARY SMELTING & REFINING OF NONFERROUS METALS [3341]'
#  'SECURITY & COMMODITY BROKERS, DEALERS, EXCHANGES & SERVICES [6200]'
#  'SECURITY BROKERS, DEALERS & FLOTATION COMPANIES [6211]'
#  'SEMICONDUCTORS & RELATED DEVICES [3674]'
#  'SERVICES-ADVERTISING AGENCIES [7311]' 'SERVICES-ADVERTISING [7310]'
#  'SERVICES-ALLIED TO MOTION PICTURE PRODUCTION [7819]'
#  'SERVICES-AMUSEMENT & RECREATION SERVICES [7900]'
#  'SERVICES-AUTO RENTAL & LEASING (NO DRIVERS) [7510]'
#  'SERVICES-AUTOMOTIVE REPAIR, SERVICES & PARKING [7500]'
#  'SERVICES-BUSINESS SERVICES, NEC [7389]'
#  'SERVICES-CHILD DAY CARE SERVICES [8351]'
#  'SERVICES-COMMERCIAL PHYSICAL & BIOLOGICAL RESEARCH [8731]'
#  'SERVICES-COMPUTER INTEGRATED SYSTEMS DESIGN [7373]'
#  'SERVICES-COMPUTER PROCESSING & DATA PREPARATION [7374]'
#  'SERVICES-COMPUTER PROGRAMMING SERVICES [7371]'
#  'SERVICES-COMPUTER PROGRAMMING, DATA PROCESSING, ETC. [7370]'
#  'SERVICES-CONSUMER CREDIT REPORTING, COLLECTION AGENCIES [7320]'
#  'SERVICES-DETECTIVE, GUARD & ARMORED CAR SERVICES [7381]'
#  'SERVICES-DIRECT MAIL ADVERTISING SERVICES [7331]'
#  'SERVICES-EDUCATIONAL SERVICES [8200]'
#  'SERVICES-EMPLOYMENT AGENCIES [7361]'
#  'SERVICES-ENGINEERING SERVICES [8711]'
#  'SERVICES-ENGINEERING, ACCOUNTING, RESEARCH, MANAGEMENT [8700]'
#  'SERVICES-EQUIPMENT RENTAL & LEASING, NEC [7359]'
#  'SERVICES-FACILITIES SUPPORT MANAGEMENT SERVICES [8744]'
#  'SERVICES-GENERAL MEDICAL & SURGICAL HOSPITALS, NEC [8062]'
#  'SERVICES-HEALTH SERVICES [8000]' 'SERVICES-HELP SUPPLY SERVICES [7363]'
#  'SERVICES-HOME HEALTH CARE SERVICES [8082]' 'SERVICES-HOSPITALS [8060]'
#  'SERVICES-LEGAL SERVICES [8111]'
#  'SERVICES-MAILING, REPRODUCTION, COMMERCIAL ART & PHOTOGRAPHY [7330]'
#  'SERVICES-MANAGEMENT CONSULTING SERVICES [8742]'
#  'SERVICES-MANAGEMENT SERVICES [8741]'
#  'SERVICES-MEDICAL LABORATORIES [8071]'
#  'SERVICES-MEMBERSHIP SPORTS & RECREATION CLUBS [7997]'
#  'SERVICES-MISC HEALTH & ALLIED SERVICES, NEC [8090]'
#  'SERVICES-MISCELLANEOUS AMUSEMENT & RECREATION [7990]'
#  'SERVICES-MISCELLANEOUS BUSINESS SERVICES [7380]'
#  'SERVICES-MISCELLANEOUS EQUIPMENT RENTAL & LEASING [7350]'
#  'SERVICES-MISCELLANEOUS REPAIR SERVICES [7600]'
#  'SERVICES-MOTION PICTURE & VIDEO TAPE DISTRIBUTION [7822]'
#  'SERVICES-MOTION PICTURE & VIDEO TAPE PRODUCTION [7812]'
#  'SERVICES-MOTION PICTURE THEATERS [7830]'
#  'SERVICES-NURSING & PERSONAL CARE FACILITIES [8050]'
#  'SERVICES-OFFICES & CLINICS OF DOCTORS OF MEDICINE [8011]'
#  'SERVICES-PERSONAL SERVICES [7200]'
#  'SERVICES-PREPACKAGED SOFTWARE [7372]'
#  'SERVICES-RACING, INCLUDING TRACK OPERATION [7948]'
#  'SERVICES-SERVICES, NEC [8900]'
#  'SERVICES-SKILLED NURSING CARE FACILITIES [8051]'
#  'SERVICES-SPECIALTY OUTPATIENT FACILITIES, NEC [8093]'
#  'SERVICES-TESTING LABORATORIES [8734]'
#  'SERVICES-TO DWELLINGS & OTHER BUILDINGS [7340]'
#  'SERVICES-VIDEO TAPE RENTAL [7841]'
#  'SHIP & BOAT BUILDING & REPAIRING [3730]'
#  'SHORT-TERM BUSINESS CREDIT INSTITUTIONS [6153]'
#  'SOAP, DETERGENT, CLEANING PREPARATIONS, PERFUMES, COSMETICS [2840]'
#  'SPECIAL INDUSTRY MACHINERY (NO METALWORKING MACHINERY) [3550]'
#  'SPECIAL INDUSTRY MACHINERY, NEC [3559]'
#  'SPECIALTY CLEANING, POLISHING AND SANITATION PREPARATIONS [2842]'
#  'SPORTING & ATHLETIC GOODS, NEC [3949]' 'STATE COMMERCIAL BANKS [6022]'
#  'STEEL PIPE & TUBES [3317]'
#  'STEEL WORKS, BLAST FURNACES  ROLLING MILLS (COKE OVENS) [3312]'
#  'STEEL WORKS, BLAST FURNACES & ROLLING & FINISHING MILLS [3310]'
#  'SUGAR & CONFECTIONERY PRODUCTS [2060]' 'SURETY INSURANCE [6351]'
#  'SURGICAL & MEDICAL INSTRUMENTS & APPARATUS [3841]'
#  'SWITCHGEAR & SWITCHBOARD APPARATUS [3613]'
#  'TELEGRAPH & OTHER MESSAGE COMMUNICATIONS [4822]'
#  'TELEPHONE & TELEGRAPH APPARATUS [3661]'
#  'TELEPHONE COMMUNICATIONS (NO RADIO TELEPHONE) [4813]'
#  'TELEVISION BROADCASTING STATIONS [4833]' 'TEXTILE MILL PRODUCTS [2200]'
#  'TIRES AND INNER TUBES [3011]' 'TITLE INSURANCE [6361]'
#  'TOBACCO PRODUCTS [2100]'
#  'TOTALIZING FLUID METERS & COUNTING DEVICES [3824]'
#  'TRANSPORTATION SERVICES [4700]' 'TRUCK & BUS BODIES [3713]'
#  'TRUCK TRAILERS [3715]' 'TRUCKING & COURIER SERVICES (NO AIR) [4210]'
#  'TRUCKING (NO LOCAL) [4213]' 'UNSUPPORTED PLASTICS FILM & SHEET [3081]'
#  'WATCHES, CLOCKS, CLOCKWORK OPERATED DEVICES/PARTS [3873]'
#  'WATER SUPPLY [4941]' 'WATER TRANSPORTATION [4400]'
#  'WATER, SEWER, PIPELINE, COMM AND POWER LINE CONSTRUCTION [1623]'
#  'WHOLESALE-APPAREL, PIECE GOODS & NOTIONS [5130]'
#  'WHOLESALE-BEER, WINE & DISTILLED ALCOHOLIC BEVERAGES [5180]'
#  'WHOLESALE-CHEMICALS & ALLIED PRODUCTS [5160]'
#  'WHOLESALE-COMPUTER & PERIPHERAL EQUIPMENT & SOFTWARE [5045]'
#  "WHOLESALE-DRUGS PROPRIETARIES & DRUGGISTS' SUNDRIES [5122]"
#  'WHOLESALE-DURABLE GOODS [5000]' 'WHOLESALE-DURABLE GOODS, NEC [5099]'
#  'WHOLESALE-ELECTRICAL APPARATUS & EQUIPMENT, WIRING SUPPLIES [5063]'
#  'WHOLESALE-ELECTRONIC PARTS & EQUIPMENT, NEC [5065]'
#  'WHOLESALE-FARM PRODUCT RAW MATERIALS [5150]'
#  'WHOLESALE-GROCERIES & GENERAL LINE [5141]'
#  'WHOLESALE-GROCERIES & RELATED PRODUCTS [5140]'
#  'WHOLESALE-HARDWARE & PLUMBING & HEATING EQUIPMENT & SUPPLIES [5070]'
#  'WHOLESALE-HARDWARE [5072]'
#  'WHOLESALE-INDUSTRIAL MACHINERY & EQUIPMENT [5084]'
#  'WHOLESALE-JEWELRY, WATCHES, PRECIOUS STONES & METALS [5094]'
#  'WHOLESALE-LUMBER & OTHER CONSTRUCTION MATERIALS [5030]'
#  'WHOLESALE-LUMBER, PLYWOOD, MILLWORK & WOOD PANELS [5031]'
#  'WHOLESALE-MACHINERY, EQUIPMENT & SUPPLIES [5080]'
#  'WHOLESALE-MEDICAL, DENTAL & HOSPITAL EQUIPMENT & SUPPLIES [5047]'
#  'WHOLESALE-METALS SERVICE CENTERS & OFFICES [5051]'
#  'WHOLESALE-METALS, MINERALS (NO PETROLEUM) [5050]'
#  'WHOLESALE-MISC DURABLE GOODS [5090]'
#  'WHOLESALE-MISCELLANEOUS NONDURABLE GOODS [5190]'
#  'WHOLESALE-MOTOR VEHICLE SUPPLIES & NEW PARTS [5013]'
#  'WHOLESALE-MOTOR VEHICLES & MOTOR VEHICLE PARTS & SUPPLIES [5010]'
#  'WHOLESALE-PAPER AND PAPER PRODUCTS [5110]'
#  'WHOLESALE-PETROLEUM & PETROLEUM PRODUCTS (NO BULK STATIONS) [5172]'
#  'WHOLESALE-PETROLEUM BULK STATIONS & TERMINALS [5171]'
#  'WHOLESALE-PROFESSIONAL & COMMERCIAL EQUIPMENT & SUPPLIES [5040]'
#  "WOMEN'S, MISSES', AND JUNIORS OUTERWEAR [2330]"
#  "WOMEN'S, MISSES', CHILDREN'S & INFANTS' UNDERGARMENTS [2340]"
#  'WOOD HOUSEHOLD FURNITURE, (NO UPHOLSTERED) [2511]'
#  'X-RAY APPARATUS & TUBES & RELATED IRRADIATION APPARATUS [3844]']
